export const userDb = [
    {
        id:1,
        name: '  Ignacio Robles',
        category: 'Gasista',
        description: 'Matriculado, San Miguel de Tucuman, amplia experiencia, cobro economicos',
        rating: 3,

    },
    {
        id:2,
        name: '  Brenda Leone',
        category: 'Electricista',
        description: 'Especialista con matricula, Yerba Buena, excelentes referencias',
        rating: 4,
    },
    {
        id:3,
        name: '  Luis Nieva',
        category: 'Albañil',
        description: 'Con titulo, Yerba Buena, prolijidad y puntualidad (Soy el mejor) ',
        rating: 5,
    },
    {
        id:4,
        name: 'Rodrigo Cabrera Romero',
        category: 'Gasista',
        description: 'Me encuentro en burruyacu, 37 años, con 11 de experiencia',
        rating: 4,
    },
    {
        id:5,
        name: 'Víctor Ruiz Serrano',
        category: 'Electricista',
        description: 'Excelentes referencias, San Miguel de Tucuman',
        rating: 3,
    },
    {
        id:6,
        name: 'Samuel Ferrer Gutierrez',
        category: 'Electricista',
        description: 'Titulo en ingenieria, Yerba Buena, trato cordial',
        rating: 3,
    },
    {
        id:7,
        name: 'Ian Gutierrez Martin',
        category: 'Albañil',
        description: '10 años de experiencia en el campo, San Miguel y Yerba Buena',
        rating: 4,
    },
    {
        id:8,
        name: 'Aleix Navarro Nuñez',
        category: 'Gasista',
        description: 'Matriculado, 55 años, mucha experiencia, San Miguel de Tucuman',
        rating: 5,
    },
    {
        id:9,
        name: 'Diego Blanco Flores',
        category: 'Plomero',
        description: 'Con diploma, movilidad por zona centrica, 5 años de experiencia',
        rating: 4,
    },
    {
        id:10,
        name: 'Éric Sola Lopez',
        category: 'Electricista',
        description: 'Yerba Buena, excelentes referencias, precio ajustado',
        rating: 3,
    },
    {
        id:11,
        name: 'Carlos Marquez Alonso',
        category: 'Plomero',
        description: 'Plomero con rango de accion de san miguel de tucuman, excelente servicio',
        rating: 2,
    },
    {
        id:12,
        name: 'Aaron Morales Suarez',
        category: 'Albañil',
        description: 'Albañil c/experiencia en el rubro, excelente trato y referencias',
        rating: 1,
    },
    {
        id:13,
        name: 'Éric Garrido Blanco',
        category: 'Gasista',
        description: 'Matriculado, zona centrica, 15 años de experiencia',
        rating: 5,
    },
    {
        id:14,
        name: 'Fernando Marti Santiago',
        category: 'Electricista',
        description: 'Precios accesibles, zona de yerba buena, buenos precios',
        rating: 4,
    },
    {
        id:15,
        name: 'Unai Gonzalez Esteban',
        category: 'Albañil',
        description: 'Albañil, zona centrica, excelentes referencias, 20 años avalan mi servicio',
        rating: 2,
    },
    {
        id:16,
        name: 'Ignacio Graneros',
        category: 'Mecanico',
        description: 'Mecanico, nuevo en el rubro, 20 años, sin experiencia',
        rating: 1,
    },
    {
        id:17,
        name:'Rodrigo Rivadeneira',
        category: 'Carpintero',
        description: 'Amplia experiencia, muy buena disponibilidad horaria',
        rating: 5,
    },
    {
        id:18,
        name: 'Franco Boquete',
        category: 'Pintor',
        description: 'Precios por día o por trabajo, zona Las Talitas',
        rating: 3,
    },
    {
        id:19,
        name: 'Diego Cordoba',
        category: 'Carpintero',
        description: 'Trabajos especializados, seriedad laboral',
        rating: 4,
    },
    {
        id:20,
        name: 'Agustin Armani',
        category: 'Tapicero',
        description: 'Precios razonables, exelntes referencias, muy profesional',
        rating: 5,
    },
    {
        id:21,
        name: 'Gonzalo Pais',
        category: 'Pintor',
        description: 'Trabajos de muy buena calidad, rendimiento optimo',
        rating: 2,
    },
];