export const userDb = [
    {
        id:1,
        name: 'Ignacio Robles',
        category: 'Gasista',
        description: 'Soy gasista matriculado, mi zona se encuentra en el gran san miguel de tucuman, amplia experiencia en el sector, tengo 44 años, cobro economicos',
        rating: 3,

    },
    {
        id:2,
        name: 'Brenda Leone',
        category: 'Electricista',
        description: 'Soy especialista en electricidad con matricula, mi zona se encuentra en yerba buena, amplia experiencia en el sector, tengo 30 años, excelentes referencias',
        rating: 4,
    },
    {
        id:3,
        name: 'Luis Nieva',
        category: 'Albañil',
        description: 'Soy albañil c/titulo, mi zona es concepcion, excelentes referencias, 24 años, prolijidad y puntualidad',
        rating: 5,
    },
    {
        id:4,
        name: 'Rodrigo Cabrera Romero',
        category: 'Gasista',
        description: 'Soy gasista, me encuentro en burruyacu, 37 años c/11 de experiencia',
        rating: 4,
    },
    {
        id:5,
        name: 'Víctor Ruiz Serrano',
        category: 'Electricista',
        description: 'Electricista con excelentes referencias, con movilidad propia por el san miguel de tucuman, veo tus facturas de luz y como mejorar el consumo',
        rating: 3,
    },
    {
        id:6,
        name: 'Samuel Ferrer Gutierrez',
        category: 'Electricista',
        description: 'Electricista, con titulo en ingenieria, zona de yerba buena, excelente trabajo y trato cordial',
        rating: 3,
    },
    {
        id:7,
        name: 'Ian Gutierrez Martin',
        category: 'Albañil',
        description: 'Prestador de servicios de albañileria, 10 años de experiencia en el campo, mi zona es todo san miguel y yerba buena',
        rating: 4,
    },
    {
        id:8,
        name: 'Aleix Navarro Nuñez',
        category: 'Gasista',
        description: 'Gasista matriculado, 55 años, mucha experiencia en el rubro, me muevo por la zona de san miguel de tucuman',
        rating: 5,
    },
    {
        id:8,
        name: 'Diego Blanco Flores',
        category: 'Plomero',
        description: 'Plomero c/diploma, movilidad por zona centrica, 5 años de experiencia avalan mi servicio',
        rating: 4,
    },
    {
        id:9,
        name: 'Éric Sola Lopez',
        category: 'Electricista',
        description: 'Electricista con movilidad por yerba buena, excelentes referencias, precio ajustado y trato cordial',
        rating: 3,
    },
    {
        id:10,
        name: 'Carlos Marquez Alonso',
        category: 'Plomero',
        description: 'Plomero con rango de accion de san miguel de tucuman, excelente servicio',
        rating: 2,
    },
    {
        id:11,
        name: 'Aaron Morales Suarez',
        category: 'Albañil',
        description: 'Albañil c/experiencia en el rubro, excelente trato y referencias',
        rating: 1,
    },
    {
        id:12,
        name: 'Éric Garrido Blanco',
        category: 'Gasista',
        description: 'Gasista matriculado, zona centrica, precios accesibles, 15 años de experiencia',
        rating: 5,
    },
    {
        id:13,
        name: 'Fernando Marti Santiago',
        category: 'Electricista',
        description: 'Electricista, precios accesibles, zona de yerba buena, buenos precios',
        rating: 4,
    },
    {
        id:14,
        name: 'Unai Gonzalez Esteban',
        category: 'Albañil',
        description: 'Albañil, zona centrica, excelentes referencias, 20 años avalan mi servicio',
        rating: 2,
    },
];